
name: Build and Release APK

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          pip install -r requirements.txt

      - name: Build APK
        run: |
          flet build apk --project qiyam-time --build-number 1 --build-version 1.0.0

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: qiyam-time-apk
          path: build/apk/qiyam_time-*.apk
